//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySolution.ServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/WcfService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ParallProcessing", ReplyAction="http://tempuri.org/IService1/ParallProcessingResponse")]
        System.Collections.Generic.Dictionary<string, int> ParallProcessing();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ParallProcessing", ReplyAction="http://tempuri.org/IService1/ParallProcessingResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> ParallProcessingAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ParallProcessingStr", ReplyAction="http://tempuri.org/IService1/ParallProcessingStrResponse")]
        System.Collections.Generic.Dictionary<string, int> ParallProcessingStr(string stringsText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/ParallProcessingStr", ReplyAction="http://tempuri.org/IService1/ParallProcessingStrResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> ParallProcessingStrAsync(string stringsText);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addStr", ReplyAction="http://tempuri.org/IService1/addStrResponse")]
        void addStr(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/addStr", ReplyAction="http://tempuri.org/IService1/addStrResponse")]
        System.Threading.Tasks.Task addStrAsync(string str);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        MySolution.ServiceReference.CompositeType GetDataUsingDataContract(MySolution.ServiceReference.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<MySolution.ServiceReference.CompositeType> GetDataUsingDataContractAsync(MySolution.ServiceReference.CompositeType composite);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : MySolution.ServiceReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<MySolution.ServiceReference.IService1>, MySolution.ServiceReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, int> ParallProcessing() {
            return base.Channel.ParallProcessing();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> ParallProcessingAsync() {
            return base.Channel.ParallProcessingAsync();
        }
        
        public System.Collections.Generic.Dictionary<string, int> ParallProcessingStr(string stringsText) {
            return base.Channel.ParallProcessingStr(stringsText);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, int>> ParallProcessingStrAsync(string stringsText) {
            return base.Channel.ParallProcessingStrAsync(stringsText);
        }
        
        public void addStr(string str) {
            base.Channel.addStr(str);
        }
        
        public System.Threading.Tasks.Task addStrAsync(string str) {
            return base.Channel.addStrAsync(str);
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public MySolution.ServiceReference.CompositeType GetDataUsingDataContract(MySolution.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<MySolution.ServiceReference.CompositeType> GetDataUsingDataContractAsync(MySolution.ServiceReference.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
    }
}
